name: sand_gravel_app
description: TranspoGest - Application de gestion Transport & Matériaux BTP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  intl: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env


  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
